"""add company platform configuration

Revision ID: fa39a0d85305
Revises: 878d64f2fdbc
Create Date: 2026-08-30 14:17:13.191071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa39a0d85305'
down_revision: Union[str, Sequence[str], None] = '878d64f2fdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "companies",
        sa.Column(
            "platform",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.add_column(
        "companies",
        sa.Column(
            "adapter_config",
            sa.JSON(),
            nullable=True,
        ),
    )

    op.add_column(
        "companies",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.add_column(
        "companies",
        sa.Column(
            "last_scraped_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Existing companies are active by default.
    op.alter_column(
        "companies",
        "is_active",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_scraped_at')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'adapter_config')
    op.drop_column('companies', 'platform')
    # ### end Alembic commands ###
